name: Deploy Quarto project to GitHub Pages

on:
  workflow_dispatch:
  
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Set up R dependencies
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Explicitly install libcurl on the runner
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev
      - name: Setup R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
      
      # Run the R script to fetch/upload news JSON
      - name: Pull news data
        run: Rscript theNews.R

      # Push JSON to repo
      - uses: stefanzweifel/git-auto-commit-action@v5
